### ISSUE TITLE
Newbie

### ISSUE THREAD

**Issue by utkarshkg** [hthm00/AutoSnuckls#1]
hey its really good to see you come up with this auto tool...thanks for releasing in public...but friend i am wondering how can i use this? any procedure steps will be appreciable...thanks by heart..and how do u solving captchas?

**Comment by hthm00** [comment]
This auto is out-dated since it was created 2 years ago. I didn't implemented captcha solving to this auto but it can be done using DeathByCaptcha service. Thanks for interest.
